#
# Module manifest for module 'WSLC'
#
# Generated by: Microsoft Corporation
#

@{

# Script module or binary module file associated with this manifest
RootModule = 'WSLC.PowerShell.dll'

# Version number of this module
ModuleVersion = '1.0.0'

# Supported PSEditions
CompatiblePSEditions = @('Core', 'Desktop')

# ID used to uniquely identify this module
GUID = '278c74c6-9601-4c73-b3d4-90391b95ce10'

# Author of this module
Author = 'Microsoft Corporation'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = 'Copyright (c) Microsoft Corporation.'

# Description of the functionality provided by this module
Description = 'This package contains PowerShell cmdlets for Microsoft.WSL.Containers.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = 'WSLC.Types.ps1xml'

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = @(
    'WSLC.Format.ps1xml'
)

# Cmdlets to export from this module
CmdletsToExport = @(
    'Connect-ContainerRegistry',
    'Disconnect-ContainerRegistry',
    'Get-ContainerSession',
    'Get-Container',
    'Get-ContainerDetail',
    'Get-ContainerImage',
    'Get-ContainerComponent',
    'Get-ContainerVersion',
    'Add-ContainerImageTag',
    'Import-ContainerImage',
    'Install-ContainerFeature',
    'Invoke-ContainerImage',
    'New-Container',
    'New-ContainerSession',
    'Remove-Container',
    'Remove-ContainerImage',
    'Request-ContainerImage',
    'Start-Container',
    'Start-ContainerProcess',
    'Start-ContainerSession',
    'Stop-Container',
    'Stop-ContainerSession',
    'Submit-ContainerImage',
    'Wait-Container'
)

# Aliases to export from this module
AliasesToExport = @(
    'Login-ContainerRegistry',
    'Logout-ContainerRegistry',
    'Pull-ContainerImage',
    'Push-ContainerImage',
    'Tag-ContainerImage',
    'Load-ContainerImage',
    'Run-ContainerImage',
    'Run-Container',
    'Exec-Container'
)

PrivateData = @{
    PSData = @{
        ProjectUri = 'https://github.com/microsoft/WSL'
    }
}

# Default prefix for commands exported from this module (New-Container -> New-WslcContainer),
# so it coexists with Docker.PowerShell. Override using Import-Module -Prefix.
DefaultCommandPrefix = 'Wslc'

}
