<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <Description>Docker PowerShell is a module that allows you to interact with the Docker Remote API via a PowerShell.</Description>
    <Version>1.0.0</Version>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>Docker.PowerShell</AssemblyName>
    <PackageId>Docker</PackageId>
    <!--<PackageTargetFallback Condition=" '$(TargetFramework)' == 'netstandard2.0' ">$(PackageTargetFallback);portable-net45+win8</PackageTargetFallback>-->
    <GenerateAssemblyTitleAttribute>false</GenerateAssemblyTitleAttribute>
    <GenerateAssemblyDescriptionAttribute>false</GenerateAssemblyDescriptionAttribute>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <GenerateAssemblyCopyrightAttribute>false</GenerateAssemblyCopyrightAttribute>
    <RestoreProjectStyle>PackageReference</RestoreProjectStyle>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <LangVersion>latest</LangVersion>
    <PackageLicenseUrl>https://github.com/aberus/Containers-PowerShell/blob/master/LICENSE</PackageLicenseUrl>
    <Copyright>Copyright Microsoft 2015</Copyright>
    <PackageTags>Docker Container C# .NET PowerShell</PackageTags>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/aberus/Containers-PowerShell</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <None Update="Docker.psd1;Docker.psm1;Docker.Format.ps1xml">
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Docker.DotNet.Enhanced" Version="4.3.3" PrivateAssets="All" />
    <PackageReference Include="Docker.DotNet.Enhanced.X509" Version="4.3.3" PrivateAssets="All" />
    <PackageReference Include="PowerShellStandard.Library" Version="5.1.1" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tar\Tar.csproj" />
  </ItemGroup>

</Project>